#include "arch_irq_handler.h"

#if !defined (GD32F450) && !defined (GD32F405) && !defined (GD32F407) && !defined (GD32F470) && !defined (GD32F425) && !defined (GD32F427)
#define GD32F427
#endif

#include "gd32f4xx.h"
#include <stddef.h>

#define ARCH_IRQ_HANDLER_COUNT ( (uint32_t)( FPU_IRQn + 1 ) )

static void (*irq_handler_table[ARCH_IRQ_HANDLER_COUNT])(void* user_data) = { NULL };
static void* irq_user_data_table[ARCH_IRQ_HANDLER_COUNT] = { NULL };

void arch_irq_handler_register( IRQn_Type irqn , void (*handler)(void* user_data) , void* user_data )
{
    if( (uint32_t)irqn < ARCH_IRQ_HANDLER_COUNT )
    {
        irq_handler_table[irqn] = handler;
        irq_user_data_table[irqn] = user_data;
    }
}

static void call_arch_irq_handler( uint32_t irqn )
{
    if( ( irqn < ARCH_IRQ_HANDLER_COUNT ) && ( irq_handler_table[irqn] != NULL ) )
    {
        irq_handler_table[irqn]( irq_user_data_table[irqn] );
    }
}

#define ARCH_DECLARE_IRQ_HANDLER(name, irqn) \
    void name(void)                          \
    {                                        \
        call_arch_irq_handler( (uint32_t)( irqn ) ); \
    }

ARCH_DECLARE_IRQ_HANDLER( WWDGT_IRQHandler, WWDGT_IRQn )
ARCH_DECLARE_IRQ_HANDLER( LVD_IRQHandler, LVD_IRQn )
ARCH_DECLARE_IRQ_HANDLER( TAMPER_STAMP_IRQHandler, TAMPER_STAMP_IRQn )
ARCH_DECLARE_IRQ_HANDLER( RTC_WKUP_IRQHandler, RTC_WKUP_IRQn )
ARCH_DECLARE_IRQ_HANDLER( FMC_IRQHandler, FMC_IRQn )
ARCH_DECLARE_IRQ_HANDLER( RCU_CTC_IRQHandler, RCU_CTC_IRQn )
ARCH_DECLARE_IRQ_HANDLER( EXTI0_IRQHandler, EXTI0_IRQn )
ARCH_DECLARE_IRQ_HANDLER( EXTI1_IRQHandler, EXTI1_IRQn )
ARCH_DECLARE_IRQ_HANDLER( EXTI2_IRQHandler, EXTI2_IRQn )
ARCH_DECLARE_IRQ_HANDLER( EXTI3_IRQHandler, EXTI3_IRQn )
ARCH_DECLARE_IRQ_HANDLER( EXTI4_IRQHandler, EXTI4_IRQn )
ARCH_DECLARE_IRQ_HANDLER( DMA0_Channel0_IRQHandler, DMA0_Channel0_IRQn )
ARCH_DECLARE_IRQ_HANDLER( DMA0_Channel1_IRQHandler, DMA0_Channel1_IRQn )
ARCH_DECLARE_IRQ_HANDLER( DMA0_Channel2_IRQHandler, DMA0_Channel2_IRQn )
ARCH_DECLARE_IRQ_HANDLER( DMA0_Channel3_IRQHandler, DMA0_Channel3_IRQn )
ARCH_DECLARE_IRQ_HANDLER( DMA0_Channel4_IRQHandler, DMA0_Channel4_IRQn )
ARCH_DECLARE_IRQ_HANDLER( DMA0_Channel5_IRQHandler, DMA0_Channel5_IRQn )
ARCH_DECLARE_IRQ_HANDLER( DMA0_Channel6_IRQHandler, DMA0_Channel6_IRQn )
ARCH_DECLARE_IRQ_HANDLER( ADC_IRQHandler, ADC_IRQn )
ARCH_DECLARE_IRQ_HANDLER( CAN0_TX_IRQHandler, CAN0_TX_IRQn )
ARCH_DECLARE_IRQ_HANDLER( CAN0_RX0_IRQHandler, CAN0_RX0_IRQn )
ARCH_DECLARE_IRQ_HANDLER( CAN0_RX1_IRQHandler, CAN0_RX1_IRQn )
ARCH_DECLARE_IRQ_HANDLER( CAN0_EWMC_IRQHandler, CAN0_EWMC_IRQn )
ARCH_DECLARE_IRQ_HANDLER( EXTI5_9_IRQHandler, EXTI5_9_IRQn )
ARCH_DECLARE_IRQ_HANDLER( TIMER0_BRK_TIMER8_IRQHandler, TIMER0_BRK_TIMER8_IRQn )
ARCH_DECLARE_IRQ_HANDLER( TIMER0_UP_TIMER9_IRQHandler, TIMER0_UP_TIMER9_IRQn )
ARCH_DECLARE_IRQ_HANDLER( TIMER0_TRG_CMT_TIMER10_IRQHandler, TIMER0_TRG_CMT_TIMER10_IRQn )
ARCH_DECLARE_IRQ_HANDLER( TIMER0_Channel_IRQHandler, TIMER0_Channel_IRQn )
ARCH_DECLARE_IRQ_HANDLER( TIMER1_IRQHandler, TIMER1_IRQn )
ARCH_DECLARE_IRQ_HANDLER( TIMER2_IRQHandler, TIMER2_IRQn )
ARCH_DECLARE_IRQ_HANDLER( TIMER3_IRQHandler, TIMER3_IRQn )
ARCH_DECLARE_IRQ_HANDLER( I2C0_EV_IRQHandler, I2C0_EV_IRQn )
ARCH_DECLARE_IRQ_HANDLER( I2C0_ER_IRQHandler, I2C0_ER_IRQn )
ARCH_DECLARE_IRQ_HANDLER( I2C1_EV_IRQHandler, I2C1_EV_IRQn )
ARCH_DECLARE_IRQ_HANDLER( I2C1_ER_IRQHandler, I2C1_ER_IRQn )
ARCH_DECLARE_IRQ_HANDLER( SPI0_IRQHandler, SPI0_IRQn )
ARCH_DECLARE_IRQ_HANDLER( SPI1_IRQHandler, SPI1_IRQn )
ARCH_DECLARE_IRQ_HANDLER( USART0_IRQHandler, USART0_IRQn )
ARCH_DECLARE_IRQ_HANDLER( USART1_IRQHandler, USART1_IRQn )
ARCH_DECLARE_IRQ_HANDLER( USART2_IRQHandler, USART2_IRQn )
ARCH_DECLARE_IRQ_HANDLER( EXTI10_15_IRQHandler, EXTI10_15_IRQn )
ARCH_DECLARE_IRQ_HANDLER( RTC_Alarm_IRQHandler, RTC_Alarm_IRQn )
ARCH_DECLARE_IRQ_HANDLER( USBFS_WKUP_IRQHandler, USBFS_WKUP_IRQn )
ARCH_DECLARE_IRQ_HANDLER( TIMER7_BRK_TIMER11_IRQHandler, TIMER7_BRK_TIMER11_IRQn )
ARCH_DECLARE_IRQ_HANDLER( TIMER7_UP_TIMER12_IRQHandler, TIMER7_UP_TIMER12_IRQn )
ARCH_DECLARE_IRQ_HANDLER( TIMER7_TRG_CMT_TIMER13_IRQHandler, TIMER7_TRG_CMT_TIMER13_IRQn )
ARCH_DECLARE_IRQ_HANDLER( TIMER7_Channel_IRQHandler, TIMER7_Channel_IRQn )
ARCH_DECLARE_IRQ_HANDLER( DMA0_Channel7_IRQHandler, DMA0_Channel7_IRQn )
ARCH_DECLARE_IRQ_HANDLER( EXMC_IRQHandler, EXMC_IRQn )
ARCH_DECLARE_IRQ_HANDLER( SDIO_IRQHandler, SDIO_IRQn )
ARCH_DECLARE_IRQ_HANDLER( TIMER4_IRQHandler, TIMER4_IRQn )
ARCH_DECLARE_IRQ_HANDLER( SPI2_IRQHandler, SPI2_IRQn )
ARCH_DECLARE_IRQ_HANDLER( UART3_IRQHandler, UART3_IRQn )
ARCH_DECLARE_IRQ_HANDLER( UART4_IRQHandler, UART4_IRQn )
ARCH_DECLARE_IRQ_HANDLER( TIMER5_DAC_IRQHandler, TIMER5_DAC_IRQn )
ARCH_DECLARE_IRQ_HANDLER( TIMER6_IRQHandler, TIMER6_IRQn )
ARCH_DECLARE_IRQ_HANDLER( DMA1_Channel0_IRQHandler, DMA1_Channel0_IRQn )
ARCH_DECLARE_IRQ_HANDLER( DMA1_Channel1_IRQHandler, DMA1_Channel1_IRQn )
ARCH_DECLARE_IRQ_HANDLER( DMA1_Channel2_IRQHandler, DMA1_Channel2_IRQn )
ARCH_DECLARE_IRQ_HANDLER( DMA1_Channel3_IRQHandler, DMA1_Channel3_IRQn )
ARCH_DECLARE_IRQ_HANDLER( DMA1_Channel4_IRQHandler, DMA1_Channel4_IRQn )
ARCH_DECLARE_IRQ_HANDLER( ENET_IRQHandler, ENET_IRQn )
ARCH_DECLARE_IRQ_HANDLER( ENET_WKUP_IRQHandler, ENET_WKUP_IRQn )
ARCH_DECLARE_IRQ_HANDLER( CAN1_TX_IRQHandler, CAN1_TX_IRQn )
ARCH_DECLARE_IRQ_HANDLER( CAN1_RX0_IRQHandler, CAN1_RX0_IRQn )
ARCH_DECLARE_IRQ_HANDLER( CAN1_RX1_IRQHandler, CAN1_RX1_IRQn )
ARCH_DECLARE_IRQ_HANDLER( CAN1_EWMC_IRQHandler, CAN1_EWMC_IRQn )
ARCH_DECLARE_IRQ_HANDLER( USBFS_IRQHandler, USBFS_IRQn )
ARCH_DECLARE_IRQ_HANDLER( DMA1_Channel5_IRQHandler, DMA1_Channel5_IRQn )
ARCH_DECLARE_IRQ_HANDLER( DMA1_Channel6_IRQHandler, DMA1_Channel6_IRQn )
ARCH_DECLARE_IRQ_HANDLER( DMA1_Channel7_IRQHandler, DMA1_Channel7_IRQn )
ARCH_DECLARE_IRQ_HANDLER( USART5_IRQHandler, USART5_IRQn )
ARCH_DECLARE_IRQ_HANDLER( I2C2_EV_IRQHandler, I2C2_EV_IRQn )
ARCH_DECLARE_IRQ_HANDLER( I2C2_ER_IRQHandler, I2C2_ER_IRQn )
ARCH_DECLARE_IRQ_HANDLER( USBHS_EP1_Out_IRQHandler, USBHS_EP1_Out_IRQn )
ARCH_DECLARE_IRQ_HANDLER( USBHS_EP1_In_IRQHandler, USBHS_EP1_In_IRQn )
ARCH_DECLARE_IRQ_HANDLER( USBHS_WKUP_IRQHandler, USBHS_WKUP_IRQn )
ARCH_DECLARE_IRQ_HANDLER( USBHS_IRQHandler, USBHS_IRQn )
ARCH_DECLARE_IRQ_HANDLER( DCI_IRQHandler, DCI_IRQn )
ARCH_DECLARE_IRQ_HANDLER( TRNG_IRQHandler, TRNG_IRQn )
ARCH_DECLARE_IRQ_HANDLER( FPU_IRQHandler, FPU_IRQn )

