#!/usr/bin/env python3
"""Generate a host-loadable SEGGER OZone project for a built target."""

from __future__ import annotations

import argparse
import os
import re
import subprocess
from pathlib import Path, PureWindowsPath

from check_build_environment import decode_output


ASSIGNMENT = re.compile(r"^\s*(OZONE_DEVICE|OZONE_SVD)\s*:?=\s*(.*?)\s*(?:#.*)?$")


def read_target_config(target_mk: Path) -> dict[str, str]:
    config: dict[str, str] = {}
    for line in target_mk.read_text(encoding="utf-8").splitlines():
        match = ASSIGNMENT.match(line)
        if match:
            config[match.group(1)] = match.group(2).strip()
    if not config.get("OZONE_DEVICE"):
        raise ValueError(
            f"{target_mk} must define OZONE_DEVICE because the exact MCU cannot be inferred safely"
        )
    return config


def windows_path(path_text: str, distro: str | None) -> Path:
    """Convert a WSL path to a Windows path when invoked on Windows."""
    if os.name != "nt" or not path_text.startswith("/"):
        return Path(path_text)
    command = ["wsl.exe"]
    if distro:
        command += ["-d", distro]
    command += ["--", "wslpath", "-a", "-w", path_text]
    result = subprocess.run(
        command,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    stdout = decode_output(result.stdout).strip()
    stderr = decode_output(result.stderr).strip()
    if result.returncode != 0 or not stdout:
        raise ValueError(f"cannot convert WSL ELF path to Windows: {stderr}")
    return Path(stdout.splitlines()[-1])


def ozone_relative_path(project_dir: Path, path: Path) -> str:
    relative = os.path.relpath(path.resolve(), project_dir.resolve())
    # OZone project files use forward slashes reliably on Windows and Linux.
    return PureWindowsPath(relative).as_posix()


def wsl_path(path: Path, distro: str | None) -> str:
    """Return the Linux path embedded by a WSL-hosted compiler."""
    if os.name != "nt":
        return path.resolve().as_posix()
    command = ["wsl.exe"]
    if distro:
        command += ["-d", distro]
    command += ["--", "wslpath", "-a", "-u", path.resolve().as_posix()]
    result = subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=False)
    stdout = decode_output(result.stdout).strip()
    stderr = decode_output(result.stderr).strip()
    if result.returncode != 0 or not stdout:
        raise ValueError(f"cannot determine the WSL source path: {stderr}")
    return stdout.splitlines()[-1]


def render(
    device: str,
    elf_relative: str,
    svd: str | None,
    source_root_wsl: str,
    source_root_relative: str,
) -> str:
    svd_line = f'  Project.AddSvdFile ("{svd}");\n' if svd else ""
    return f'''/*********************************************************************
* Auto-generated by script/generate_ozone_project.py. Do not edit.
**********************************************************************/

void OnProjectLoad (void) {{
  // Translate DWARF source paths written by GCC under WSL to this Windows checkout.
  Project.AddPathSubstitute ("{source_root_wsl}", "$(ProjectDir)/{source_root_relative}");
  Project.SetDevice ("{device}");
  Project.SetHostIF ("USB", "");
  Project.SetTargetIF ("SWD");
  Project.SetTIFSpeed ("4 MHz");
{svd_line}  File.Open ("$(ProjectDir)/{elf_relative}");
}}
'''


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate an OZone .jdebug project")
    parser.add_argument("--target", required=True)
    parser.add_argument("--elf", help="ELF path; WSL paths are converted on Windows")
    parser.add_argument("--distro", help="WSL distribution used for path conversion")
    args = parser.parse_args()

    repo = Path(__file__).resolve().parent.parent
    target_mk = repo / "src" / "target" / args.target / "target.mk"
    if not target_mk.is_file():
        parser.error(f"target does not exist: {args.target}")

    try:
        config = read_target_config(target_mk)
        project_dir = repo / "build" / args.target
        elf = windows_path(args.elf, args.distro) if args.elf else project_dir / f"{args.target}.elf"
        if not elf.is_file():
            raise ValueError(f"ELF file does not exist: {elf}")
        project_dir.mkdir(parents=True, exist_ok=True)
        output = project_dir / f"{args.target}.jdebug"
        elf_relative = ozone_relative_path(project_dir, elf)
        source_root_relative = ozone_relative_path(project_dir, repo)
        source_root_wsl = wsl_path(repo, args.distro)
        output.write_text(
            render(
                config["OZONE_DEVICE"],
                elf_relative,
                config.get("OZONE_SVD"),
                source_root_wsl,
                source_root_relative,
            ),
            encoding="utf-8",
            newline="\n",
        )
    except (OSError, ValueError) as error:
        print(f"[ERROR] {error}")
        return 1

    print(f"[SUCCESS] OZone project generated: {output}")
    print(f"[INFO] ELF path in project: {elf_relative}")
    print(f"[INFO] WSL source mapping: {source_root_wsl} -> $(ProjectDir)/{source_root_relative}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
